// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/api/login.ts";
import * as $2 from "./routes/api/verify.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/login.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Header.tsx";
import * as $$2 from "./islands/Index.tsx";
import * as $$3 from "./islands/Login.tsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/api/login.ts": $1,
    "./routes/api/verify.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/login.tsx": $4,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Header.tsx": $$1,
    "./islands/Index.tsx": $$2,
    "./islands/Login.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
